# Generated by Django 2.2.6 on 2019-10-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spells5E',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('page', models.CharField(blank=True, max_length=20, null=True)),
                ('range', models.CharField(blank=True, max_length=20, null=True)),
                ('components', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('ritual', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('concentration', models.CharField(blank=True, max_length=20, null=True)),
                ('casting_time', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('school', models.CharField(blank=True, max_length=20, null=True)),
                ('char_class', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
