# Generated by Django 2.2.6 on 2019-10-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells5e',
            name='higher_level',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
