# Generated by Django 2.2.6 on 2019-11-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0004_spells5e_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells5e',
            name='oaths',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
