# Generated by Django 2.2.6 on 2019-11-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0005_spells5e_oaths'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells5e',
            name='circles',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
