# Generated by Django 2.2.6 on 2019-11-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0006_spells5e_circles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spells5e',
            name='desc',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
