# Generated by Django 2.2.6 on 2019-11-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0007_auto_20191106_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spells5e',
            name='desc',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
