# Generated by Django 2.2.6 on 2019-11-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0008_auto_20191106_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spells5e',
            name='archetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='casting_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='circles',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='components',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='concentration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='desc',
            field=models.CharField(blank=True, max_length=4500, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='domains',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='higher_level',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='material',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='oaths',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='page',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='patrons',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='ritual',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='spells5e',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
