# Generated by Django 2.2.6 on 2019-11-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0011_spells_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_spells',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
