# Generated by Django 2.2.6 on 2019-12-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0012_auto_20191117_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_spells',
            name='prepared',
            field=models.BooleanField(default=False),
        ),
    ]
