# Generated by Django 2.2.6 on 2019-10-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
