# Generated by Django 2.2.6 on 2019-10-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_sheet_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='acrobatics_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='animal_handling_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='arcana_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='athletics_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='deception_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='feat_trait',
            field=models.CharField(default='erere', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheet',
            name='history_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='insight_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='intimidation_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='investigation_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='models_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='nature_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='oth_prof_lang',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheet',
            name='pass_wisdom',
            field=models.PositiveSmallIntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheet',
            name='perception_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='performance_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='persuasion_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='religion_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='sleigth_hand_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='stealth_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='survival_circ',
            field=models.BooleanField(default=False),
        ),
    ]
