# Generated by Django 2.2.6 on 2019-10-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0005_auto_20191020_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='armor_class',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='atk_spell_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='atk_spell_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='feat_trait',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='hit_dice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='oth_prof_lang',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
