# Generated by Django 2.2.6 on 2019-10-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0006_auto_20191020_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='models_circ',
            new_name='medicine_circ',
        ),
    ]
