# Generated by Django 2.2.6 on 2019-10-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0007_auto_20191020_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
