# Generated by Django 2.2.6 on 2019-10-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0008_auto_20191020_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='charisma_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='constitution_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='dexterity_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='intelligence_circ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='wisdom_circ',
            field=models.BooleanField(default=False),
        ),
    ]
