# Generated by Django 2.2.6 on 2019-10-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0009_auto_20191020_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='charisma_circ',
            new_name='sav_charisma_circ',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='constitution_circ',
            new_name='sav_constitution_circ',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='dexterity_circ',
            new_name='sav_dexterity_circ',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='intelligence_circ',
            new_name='sav_intelligence_circ',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='wisdom_circ',
            new_name='sav_strength_circ',
        ),
        migrations.AddField(
            model_name='sheet',
            name='sav_wisdom_circ',
            field=models.BooleanField(default=False),
        ),
    ]
