# Generated by Django 2.2.6 on 2019-10-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0010_auto_20191020_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='sleigth_hand_circ',
            new_name='sleight_hand_circ',
        ),
    ]
