# -*- coding: utf-8 -*-
# Migrations file example for fixing broken ManyToManyField migration from INTEGER to VARCHAR
# Generated by Django 1.10.3 on 1970-01-01 00:00
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0012_auto_20191026_1214'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE sheet_sheet ALTER username_id TYPE varchar(32);'),
    ]