# Generated by Django 2.2.6 on 2019-10-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0012_auto_20191026_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
