# Generated by Django 2.2.6 on 2019-10-28 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0013_auto_20191028_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
