# Generated by Django 2.2.6 on 2019-12-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='bonds',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='flaws',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='ideals',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
