# Generated by Django 2.2.6 on 2019-12-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20191213_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='bonds',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='flaws',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='ideals',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='personality_traits',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
