# Generated by Django 2.2.6 on 2019-12-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20191213_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='background_story',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='oth_prof_lan',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
